### PR TITLE
王靜儀

### PR DESCRIPTION
**Pull request by docats**
API Url:
http://52.10.191.6:3000/api/attractions?page=1
http://52.10.191.6:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93
http://52.10.191.6:3000/api/attraction/100

### CODE REVIEW

**Comment by cwpeng** [comment]
1. "images" field should be an array containing image URLs separately, not a string.
2. "nextPage" of http://52.10.191.6:3000/api/attractions?page=0&keyword=%E9%A4%A8 should be 1.

fix issues and leave comment for me to review again.

**Comment by docats** [comment]
ok~

**Comment by cwpeng** [comment]
Online URLs still are not correct. Leave comment for me if you want me to review again.

**Comment by docats** [comment]
王靜儀
http://52.10.191.6:3000/api/attractions?page=1
http://52.10.191.6:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93
http://52.10.191.6:3000/api/attraction/100

**Comment by docats** [comment]
老師~我putty打開連線囉

**Review by cwpeng — APPROVED** [review]
OK.

**Pull request merged**
