### PR TITLE
王靜儀

### PR DESCRIPTION
**Pull request by docats**
王靜儀
Hello~ teacher
this is Work3 many thanks
http://52.10.191.6:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Server cannot response for now. Try to recover it and leave message for me again.

**Comment by docats** [comment]
okay I'm connect Server again :)

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Forward.

**Comment by docats** [comment]
Thanks a lot :D

**Comment by docats** [comment]
王靜儀
Hello~ teacher
this is Work4 many thanks
http://52.10.191.6:3000/

**Comment by cwpeng** [comment]
I cannot sign in in your attraction page.

**Comment by docats** [comment]
Sorry. 老師我會補上

**Comment by docats** [comment]
王靜儀
Hello~ teacher
this is Work4 many thanks
http://52.10.191.6:3000/
有再改過了

**Comment by cwpeng** [comment]
We don't need to drop and create table every time server started. It means your member data will be deleted every time server started.

Creating table should be done outside application only once, code below is unnecessary.
```
def meb(mydb):
    cursor.execute('DROP TABLE IF EXISTS member')
    sql="""CREATE TABLE member (
         id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
         name varchar(255) NOT NULL,
         email varchar(255) NOT NULL,
         password varchar(255) NOT NULL
         )"""
    cursor.execute(sql) #執行資料庫欄位設定命令
    mydb.commit() #確認執行提交到資料庫
```

**Comment by docats** [comment]
Ok

**Comment by docats** [comment]
王靜儀
Hello~ teacher
this is Work4 many thanks
http://52.10.191.6:3000/
剛剛有問了一下助教原理，學到了^^

**Review by cwpeng — APPROVED** [review]
OK. Done. Remember to merge pull request.

**Comment by docats** [comment]
ok

**Comment by docats** [comment]
I can't to merge pull request. QQ

**Comment by cwpeng** [comment]
You should resolve conflicts before merging as this page show you.

**Comment by docats** [comment]
ok many thanks

**Pull request merged**
