### PR TITLE
王靜儀

### PR DESCRIPTION
**Pull request by docats**
http://52.10.191.6:3000/
老師，這是作業2
我要先繼續下一個切版，感恩

### CODE REVIEW

**Comment by docats** [comment]
Hello~老師，我要從中壢回桃園留守我媽了，如果有需要我開AWS讓您檢視網頁，請告訴我時間點，3Q

**Comment by cwpeng** [comment]
Your server is down. We should keep server running in any time, not open for testing only.

**Comment by docats** [comment]
hi~I'm opening

**Comment by cwpeng** [comment]
It's down still.

**Comment by docats** [comment]
老師好了~你再看看QQ

**Comment by cwpeng** [comment]
1. Content of navigator, key visual section, and attraction list should align with each other inside 1200px viewport.
2. Navigator height is too large.
3. Navigator should always stayed in top when we scroll page down.
4. Your API of http://52.10.191.6:3000/api/attractions?page=1, http://52.10.191.6:3000/api/attractions?page=2, etc..., get too much data than it should be.

未命名-11

**Comment by docats** [comment]
many thanks 我會去修改一下喔

**Comment by docats** [comment]
老師，我終於改好了^^
http://52.10.191.6:3000/

**Review by cwpeng — APPROVED** [review]
OK. Finally Done. Keep Going.

**Comment by docats** [comment]
王靜儀
老師。作業3做好了喔~

**Pull request merged**
